[package]
name = "arrows"
version = "0.1.0"
edition = "2021"
default-run = "arrows"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
authors = ["Ratul Buragohain <ratul75@hotmail.com>"]


[dependencies]
async-std = {version="1.10.0",features = ["attributes"]}
futures = "0.3.17"
lazy_static = "1.4.0"
arrows_common = { git = "https://github.com/ratulb/arrows_common", branch = "main" }
rusqlite = {version="0.26.1", features = ["bundled", "blob", "serde_json"]}
serde = { version = "1.0.130", features = ["derive"]}
serde_json = {version="1.0.68"}

[dev-dependencies]
rand = "0.8.4"
