[package]
name = "samples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/" }
registry = { path = "../registry/" }
serde = {version= "1.0.130", features = ["derive"]}
serde_json = "1.0.69"
typetag = "0.1.7"
